### PR TITLE
Use classes for custom exceptions in `circular-buffer`

### LINKED ISSUE #280: Custom Exceptions are confusing
I was solving `Circular Buffer` today and had a hard time figuring out how to create custom exceptions. That is because I was expecting the matcher to match with a `custom` exception class, but what it actually does is matches with `Error` itself. 

```js
expect(()=>buffer.read()).toThrow(bufferEmptyException());
```
Note `bufferEmptyException` is a function call which gives no idea what its return type should be - `Error`/`CustomError`/`String`??

For custom exceptions in ES6, most [sources](http://exploringjs.com/es6/ch_core-features.html#sec_from-custom-error-to-error-subclass) say that this should suffice: (which is far better than its ES5 equivalent)

```js
class bufferFullException extends Error {}
```

But it does not work since [babel does not allow subclassing built-in classes](https://github.com/facebook/jest/issues/2123) (also mentioned in the [docs](https://babeljs.io/docs/usage/caveats/#classes)). I ended up using the [babel-plugin](https://github.com/loganfsmyth/babel-plugin-transform-builtin-extend) for allowing subclassing. Solution [here](http://exercism.io/submissions/d5f75a974880456db6154f39e39051f6).

Most other exercises just throw a String, while others like `wordy` and `circular-buffer` throw custom exceptions. 
So I have two questions:

* Should we have a standard way of doing exceptions in the track? Is throwing Strings OK or should we go all custom?

* For the exercises that expect custom errors, is `class bufferFullException extends Error {}` better than what we have right now? which is:
```js
const BufferFullException = () => ({
    name: "buffer full exception!",
    message: "can't write to a full buffer!"
  });
```

### PR DESCRIPTION
**Pull request by tejasbubane**
Closes #280.

### CODE REVIEW

File: exercises/circular-buffer/example.js [hunk 1]
```diff
@@ -1,25 +1,28 @@
...
+  constructor(message) {
+    super();
+    this.message = message || 'Buffer is empty.';
+  }
+};
+export class BufferFullException extends Error {
+  constructor(message) {
+    super();
+    this.message = message || 'Buffer is full.';
+  }
```
Comment (tejasbubane) [inline exercises/circular-buffer/example.js]: The constructor part is optional. But it reads nicely in the stacktrace with the message.

**Comment by tejasbubane** [comment]
For now, I have added the plugin to global `package.json` and the one of `circular-buffer`.
One problem with using the plugin in our setup is we will need to copy the main `package.json` file over in all exercises for consistency even though all won't be using custom exceptions.

File: exercises/circular-buffer/example.js [hunk 2]
```diff
@@ -1,25 +1,28 @@
...
-const BufferEmptyException = () => ({
-    name: "buffer empty exception!",
-    message: "can't read from an empty buffer!"
-  });
-
-const BufferFullException = () => ({
-    name: "buffer full exception!",
-    message: "can't write to a full buffer!"
-  });
+export class BufferEmptyException extends Error {
```
Comment (tejasbubane) [inline exercises/circular-buffer/example.js]: On second thought, should this be `BufferEmptyException` or `BufferEmptyError` (since it inherits from `Error`)?

Comment (matthewmorgan) [inline exercises/circular-buffer/example.js]: `Error` is probably better semantically.

**Comment by matthewmorgan** [comment]
@tejasbubane once this PR is merged I can re-run the makefile, which will copy the global `package.json` to each exercise, so that will fix that.  Thanks!

File: exercises/circular-buffer/example.js (hunk 2 above)
Comment (tejasbubane) [inline exercises/circular-buffer/example.js]: Changed it to `Error`.

**Comment by tejasbubane** [comment]
> I can re-run the makefile, which will copy the global package.json to each exercise, so that will fix that.

Do you think I should do that in this PR itself?

**Comment by matthewmorgan** [comment]
@tejasbubane for sure-- if you're up for that, I think it's fine in this PR.

**Comment by tejasbubane** [comment]
> if you're up for that, I think it's fine in this PR.

Done. @matthewmorgan

**Comment by rchavarria** [comment]
Sorry. I can't have an opinion on this, because I didn't try myself Jest yet. This is something I must do. I must update locally this track and run all the tests.

**Comment by matthewmorgan** [comment]
@rchavarria if you want us to wait before merging this PR until you've had a chance to run it locally, please let me know.  I'll hold off until tomorrow to give you some more time.

**Comment by joelwallis** [comment]
Same to me. Haven't tried Jest yet :(

**Comment by matthewmorgan** [comment]
@tejasbubane--do you mind resolving the merge conflicts, then I will merge it in?  Thanks!

**Comment by rchavarria** [comment]
Don't worry, don't wait for me. I'll catch up.

**Comment by matthewmorgan** [comment]
@tejasbubane bump :)

**Comment by tejasbubane** [comment]
@matthewmorgan Done. Sorry for the delay.

**Comment by rchavarria** [comment]
I'm having an error running `make test`, but as it passes on Travis, I'll merge this.

```
~/xecmascript • make test
Makefile:19: recipe for target 'test-package-files' failed
make[1]: *** [test-package-files] Error 1
Makefile:34: recipe for target 'test' failed
make: *** [test] Error 2
```

**Comment by rchavarria** [comment]
Sorry for my last comment, I didn't read #302
